global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.56.203:9090']

  - job_name: 'containers'
    static_configs:
      - targets: ['192.168.56.202:9100']

  - job_name: 'pipeline'
    static_configs:
      - targets: ['192.168.56.201:9100']
